[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install virtualenv",
  "virtualenv venv",
  "source venv/bin/activate && pip install -r requirements.txt",
  "pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot",
  "chmod +x *"
]

[start]
cmd = "python3 a.py"
