[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "python3 -m pip install -r requirements.txt",
  "chmod +x RAJ"
]

[start]
cmd = "python3 a.py"
