[phases.setup]
nixPkgs = ["python311", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "chmod +x RAJ"
]

[start]
cmd = ". venv/bin/activate && python3 a.py"
